#index:
#    path: /
#    controller: App\Controller\DefaultController::index

movies:
    type: rest
    resource: App\Controller\MoviesController

persons:
    type: rest
    prefix: /api
    resource: App\Controller\PersonsController

user:
    resource: App\Controller\UsersController
    prefix: /api
    type: rest

users_post:
    path: /api/users
    methods: [POST]
    defaults:
        _controller: App\Controller\UsersController:postUserAction
        _format: json

users_patch:
    path: /api/users/{theUser}
    methods: [PUT]
    defaults:
        _controller: App\Controller\UsersController:patchUserAction
        _format: json

tokens:
    resource: App\Controller\TokensController
    prefix: /api
    type: rest

images:
    resource: App\Controller\ImagesController
    prefix: /api/
    type: rest

images_post:
    path: /api/images
    methods: [POST]
    defaults:
        _controller: App\Controller\ImagesController:postImagesAction
        _format: json

images_upload_put:
    path: /api/images/{image}/upload
    methods: [PUT]
    defaults:
        _controller: App\Controller\ImagesController:putImageUploadAction
        _format: json

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }