#index:
#    path: /
#    controller: App\Controller\DefaultController::index

movies:
    type: rest
    prefix: /api/v1
    resource: App\Controller\MoviesController

humans:
    type: rest
    prefix: /api/v1
    resource: App\Controller\HumansController

movies_roles_post:
    path: /api/v1/movies/{movie}/roles
    methods: [POST]
    defaults:
        _controller: App\Controller\MoviesController:postMovieRolesAction
        _format: json

user:
    resource: App\Controller\UsersController
    prefix: /api/v1
    type: rest

users_post:
    path: /api/v1/users
    methods: [POST]
    defaults:
        _controller: App\Controller\UsersController:postUserAction
        _format: json

users_patch:
    path: /api/v1/users/{theUser}
    methods: [PATCH]
    defaults:
        _controller: App\Controller\UsersController:patchUserAction
        _format: json

tokens:
    resource: App\Controller\TokensController
    prefix: /api/v1
    type: rest

images:
    resource: App\Controller\ImagesController
    prefix: /api/v1
    type: rest

images_post:
    path: /api/v1/images
    methods: [POST]
    defaults:
        _controller: App\Controller\ImagesController:postImagesAction
        _format: json

images_upload_put:
    path: /api/v1/images/{image}/upload
    methods: [PUT]
    defaults:
        _controller: App\Controller\ImagesController:putImageUploadAction
        _format: json

app.swagger_ui:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }